"""Collect cohesive neutral execution contracts without duplicate discovery."""
from trial_suite_prepare_cases import TestSuitePreparation
from trial_suite_assessment_cases import TestSuiteAssessment
from trial_suite_observation_cases import TestSuiteObservation
from trial_suite_observation_client_cases import TestObservationClient
from trial_suite_prepare_review_cases import TestSuitePreparationReview
from trial_suite_observation_client_review_cases import TestObservationClientReview
from trial_suite_lineage_review_cases import TestSuiteReviewLineage
from trial_suite_dependency_admission_cases import TestSuiteDependencyAdmission, qualified_shape
